import React, { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import GlassCard from "./GlassCard";
import SectionTitle from "./SectionTitle";
import { AlertTriangle, ChevronDown } from "lucide-react";

const disclaimers = [
  {
    title: "Risk Disclaimer",
    subtitle: "Understanding the risks",
    img: "https://inoai.org/wp-content/uploads/2025/05/caution-ino-400x400.png",
    text: "It is essential to seek guidance from your own legal, financial, and tax advisors regarding any implications tied to your interactions with the InoAi (INO) token and its related ecosystem. Participating in the purchase, holding, or staking of InoAi (INO) carries inherent risks and could lead to partial or total loss of your initial capital or deposited funds. Before engaging with InoAi (INO), you should carefully assess the potential risks and decide whether such participation fits your personal risk profile and comfort level.",
  },
  {
    title: "Autonomous Analysis Disclaimer",
    subtitle: "INO's interactions",
    img: "https://inoai.org/wp-content/uploads/2025/05/ino-think-400x400.png",
    text: "The insights or actions generated by INO stem solely from its autonomous analysis. They should not be interpreted as financial, legal, or investment advice, nor should they be assumed to guarantee outcomes. All interactions remain exploratory and are subject to individual judgment and responsibility.",
  },
];

function DisclaimerCard({ item, index }) {
  const [open, setOpen] = useState(index === 0);

  return (
    <div className="border border-white/[0.04] rounded-xl overflow-hidden">
      <button
        onClick={() => setOpen(!open)}
        className="w-full flex items-center gap-4 p-4 hover:bg-white/[0.02] transition-colors text-left"
      >
        <div className="w-12 h-12 rounded-xl overflow-hidden shrink-0 bg-white/[0.04]">
          <img src={item.img} alt="" className="w-full h-full object-cover" />
        </div>
        <div className="flex-1 min-w-0">
          <p className="text-sm font-semibold text-purple-400">{item.title}</p>
          <p className="text-xs text-white/40">{item.subtitle}</p>
        </div>
        <ChevronDown className={`w-4 h-4 text-white/30 transition-transform duration-300 ${open ? "rotate-180" : ""}`} />
      </button>
      <AnimatePresence>
        {open && (
          <motion.div
            initial={{ height: 0, opacity: 0 }}
            animate={{ height: "auto", opacity: 1 }}
            exit={{ height: 0, opacity: 0 }}
            transition={{ duration: 0.3 }}
            className="overflow-hidden"
          >
            <p className="px-4 pb-4 text-sm text-white/50 leading-relaxed">
              {item.text}
            </p>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}

export default function DisclaimersSection() {
  return (
    <section className="px-4 pb-20">
      <div className="max-w-6xl mx-auto">
        <SectionTitle>
          <span className="flex items-center gap-3">
            <AlertTriangle className="w-6 h-6 text-purple-400" />
            Information
          </span>
        </SectionTitle>
        <GlassCard>
          <div className="space-y-3">
            {disclaimers.map((d, i) => (
              <DisclaimerCard key={i} item={d} index={i} />
            ))}
          </div>
        </GlassCard>
      </div>
    </section>
  );
}