import React, { useState } from 'react';
import { AlertTriangle, Info, ChevronDown } from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';

export default function Disclaimers() {
  const [open, setOpen] = useState(null);

  const items = [
    {
      id: 0,
      title: 'Risk Disclaimer',
      icon: AlertTriangle,
      color: 'text-orange-400',
      content: 'It is essential to seek guidance from your own legal, financial, and tax advisors regarding any implications tied to your interactions with the InoAi (INO) token. Participating carries inherent risks and could lead to partial or total loss of your capital. Carefully assess potential risks before engaging.'
    },
    {
      id: 1,
      title: 'Autonomous Analysis',
      icon: Info,
      color: 'text-purple-400',
      content: 'The insights generated by INO stem solely from its autonomous analysis. They should not be interpreted as financial, legal, or investment advice, nor assumed to guarantee outcomes. All interactions are exploratory and subject to individual judgment.'
    }
  ];

  return (
    <div className="rounded-2xl border border-purple-500/15 bg-white/[0.025] backdrop-blur-sm p-5 h-full flex flex-col">
      <p className="text-[10px] uppercase tracking-widest text-gray-600 mb-1">Legal</p>
      <h2 className="text-base font-bold text-white mb-4">Disclaimers</h2>
      <div className="space-y-2 flex-1">
        {items.map((d) => {
          const Icon = d.icon;
          const isOpen = open === d.id;
          return (
            <div key={d.id} className="rounded-xl border border-white/[0.06] overflow-hidden">
              <button
                onClick={() => setOpen(isOpen ? null : d.id)}
                className="w-full flex items-center gap-3 px-4 py-3 hover:bg-white/[0.03] transition-colors text-left"
              >
                <Icon className={`w-3.5 h-3.5 ${d.color} flex-shrink-0`} />
                <span className="text-xs font-semibold text-white flex-1">{d.title}</span>
                <ChevronDown className={`w-3.5 h-3.5 text-gray-600 transition-transform duration-200 flex-shrink-0 ${isOpen ? 'rotate-180' : ''}`} />
              </button>
              <AnimatePresence>
                {isOpen && (
                  <motion.div
                    initial={{ height: 0, opacity: 0 }}
                    animate={{ height: 'auto', opacity: 1 }}
                    exit={{ height: 0, opacity: 0 }}
                    transition={{ duration: 0.2 }}
                    className="overflow-hidden"
                  >
                    <p className="px-4 pb-3 text-xs text-gray-500 leading-relaxed border-t border-white/[0.05] pt-3">
                      {d.content}
                    </p>
                  </motion.div>
                )}
              </AnimatePresence>
            </div>
          );
        })}
      </div>
    </div>
  );
}